const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    GET_POSTS: 'GET_POSTS',
    GET_LIMIT_POSTS: 'GET_LIMIT_POSTS',
    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_PRICES: 'GET_PRICES',
    GET_ACREAGE: 'GET_ACREAGE'
}

export default actionTypes